name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Vet and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Enable toolchain auto (allow newer Go than runner)
        run: echo "GOTOOLCHAIN=auto" >> $GITHUB_ENV

      - name: Go env
        run: go env

      - name: Download modules
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test with race and coverage
        run: go test -race -count=1 -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
          if-no-files-found: ignore



